version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: mysql/Dockerfile
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:rw
    ports:
      - "8000:8000"
    depends_on:
            mysql:
                condition: service_healthy